version: "2.4"

services:
  influx:
    image: influxdb:1.7.4
    command: "-config /etc/influxdb/influxdb.conf"
    ports:
      - 8086:8086
    volumes:
    - type: bind
      source: "${HOME}/.stats/influxdb"
      target: /var/lib/influxdb
    - type: bind
      source: "${PWD}/influxdb.conf"
      target: /etc/influxdb/influxdb.conf
    - type: bind
      source: "${PWD}/collectd_types.db"
      target: "/usr/share/collectd/types.db"
    environment:
      INFLUXDB_DB: 'collectd'
      INFLUXDB_ADMIN_USER: 'admin'
      INFLUXDB_ADMIN_PASSWORD: 'secret'
    mem_limit: 2g
    mem_swappiness: 0

  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: "${HOME}/.stats/grafana"
        target: "/var/lib/grafana"
    environment:
      GF_SERVER_ROOT_URL: "http://localhost"
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    mem_limit: 2g
    mem_swappiness: 0

  collectd:
    image: asdfgasfhsn/collectd-docker:latest
    depends_on:
      - influx
      - grafana
    privileged: true
    volumes:
    - type: bind
      source: "/proc"
      target: "/mnt/proc"
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    mem_limit: 2g
    mem_swappiness: 0
